[project]
name = "new-react-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.12.0",
    "langchain>=1.2.1",
    "langchain-openai>=1.1.7",
    "python-dotenv>=1.2.1",
]
